# Generated by Django 5.2.7 on 2025-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
