# Generated by Django 5.2.7 on 2025-11-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada')], default='LIBRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('PREPARING', 'En preparación'), ('CHANGE_REQUESTED', 'Cambio Solicitado'), ('READY', 'Listo'), ('PAID', 'Pagado')], default='NEW', max_length=20),
        ),
    ]
