# Generated by Django 5.2.7 on 2025-11-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_table_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proposed_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('WAITER_EDITING', 'Mesero Editando'), ('PREPARING', 'En preparación'), ('CHANGE_REQUESTED', 'Cambio Solicitado'), ('READY', 'Listo'), ('PAID', 'Pagado')], default='NEW', max_length=20),
        ),
    ]
