# Generated by Django 5.2.7 on 2025-11-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_proposed_changes_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='needs_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='session_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
