# Generated by Django 5.2.7 on 2025-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivered_at_order_paid_at_order_preparing_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('WAITER_EDITING', 'Mesero Editando'), ('PREPARING', 'En preparación'), ('CHANGE_REQUESTED', 'Cambio Solicitado'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado')], default='NEW', max_length=20),
        ),
    ]
